### PR TITLE
[fix] dont render block annotation when block content is empty

### PR DESCRIPTION
**Pull request by danielmaier42**
Closes Issue #4

### CODE REVIEW

**Comment by danielmaier42** [comment]
You are right - i also recognized another thing when checking out your comment. The check only was inside of `annotateBlock` which is called by the `BlockInterfacePlugin`, but neither in `annotateContainer` nor in `annotateUiComponent` which where both called from the `Logger`.

I just pushed another commit which returns the `$content` "as is" so we wont potentially change data types. Also i added it to the `Logger` Class.

**Comment by danielmaier42** [comment]
Could anybody please review the changes and - in best case - approve them? 🙂

**Comment by maxbucknell** [comment]
Sorry @danielmaier42, I changed email servers and missed a bunch of notifications. Got your comment through this morning.

Looks great to me, thanks for the help!

**Comment by danielmaier42** [comment]
Thanks for approving my Changes @maxbucknell 🙂 
Would you close the corresponding Issue #4 ?

**Pull request merged**
